# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd680106d271ca0d7ba3da490568c5396d9649175f6fc2c5f461c3237769d25464ef08d67d61247aa9c4eac84058bc79a8479245eaf064b51aaaae6a6490b421

test:
  secret_key_base: ce74883c6b2e1ea8e65c03126e2b0adbf7131fc2462bbbc8e617d01a8db44b4ace841929da0fd07a9c2e07a20cbd24a1726e0cab4fd66a70ae13d76529a05cba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
